---
title: "LAs BEST Project"
author: "Justin Coles, Jessy Garcia, Joseph"
date: "2025-06-20"
output:
html_document: default

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r pressure, echo=FALSE}
library(ggplot2)
library(dplyr)
library(gtsummary)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
getwd()
EV_data <- read.csv("./Data/data_ZEV_asthmaED_2013_2022.csv")
```

```{r}
#Getting number of EVs per 1000 people
EV_data$nZEV1000pop <- EV_data$nZEV/EV_data$pop *1000
#RoA = Rate of Asthma
EV_data$log_AgeAdj_RoA_ED_Visit_Rate <- log(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate)
#Getting LN to help create better plots 
```

```{r}
#Summary Stats by all years
summary_stats_allyrs <- c(
summary(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate),
SD=sd(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate))

summary_stats_allyrs
#mean(41.90) --> #there are about 41.90 visits to ED per 10,000ppl
#Sd(28.98) --> there is huge variance between zip codes and ppl in ED 
```
```{r}
sum(is.na(EV_data))
```

```{r}
#Summary Stats by each years
cat("Summary Statistics of Asthma ED Visit Rates by Year:\n")
print(tapply(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate, EV_data$yr, summary, na.rm = TRUE))

cat("\nStandard Deviation by Year:\n")
print(tapply(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate , EV_data$yr , sd, na.rm = TRUE))

```

```{r}
tapply(EV_data$nZEV, EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$nZEV, EV_data$yr, sd,      na.rm = TRUE)

```
```{r}
tapply(EV_data$nZEV1000pop , EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$nZEV1000pop , EV_data$yr, sd,      na.rm = TRUE)
```
```{r} 
tapply(EV_data$pop , EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$pop , EV_data$yr, sd,      na.rm = TRUE)
```

```{r}
tapply(EV_data$percPoverty , EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$percPoverty , EV_data$yr, sd,      na.rm = TRUE)
```

```{r}
tapply(EV_data$HHincomeMedian , EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$HHincomeMedian , EV_data$yr, sd,      na.rm = TRUE)
```

```{r}
tapply(EV_data$HHincomeMean , EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$HHincomeMean , EV_data$yr, sd,      na.rm = TRUE)
```

```{r}
tapply(EV_data$EDUCpercHSplus , EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$EDUCpercHSplus , EV_data$yr, sd,      na.rm = TRUE)
```

```{r}
tapply(EV_data$EDUCpercBAplus , EV_data$yr, summary, na.rm = TRUE) 
tapply(EV_data$EDUCpercBAplus , EV_data$yr, sd,      na.rm = TRUE)
```
```{r}

#New dataset with just the variables of interest for Corr. Matrix

library(corrplot)

corr_EV_data_vars <- EV_data[, c(
  "nZEV",                      # number of electric vehicles
  "nZEV1000pop",              # EVs per 1000 people
  "pop",                      # population
  "Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate",  # asthma outcomlie
  "percPoverty",              # poverty %
  "HHincomeMedian",           # median income
  "HHincomeMean",             # mean income
  "EDUCpercHSplus",           # % with high school education or higher
  "EDUCpercBAplus"            # % with bachelor’s degree or higher
)]

corr_EV_data_matrix <- cor(corr_EV_data_vars, use = "complete.obs")
print(corr_EV_data_matrix)


```

```{r}
library(gtsummary)
library(dplyr)

EV_data %>%
  filter(yr %in% c(2013, 2017, 2022)) %>%
  mutate(yr = as.factor(yr)) %>%
  tbl_summary(
    include = c(nZEV, Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate),
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    by = yr
  ) %>%
  
  add_overall()


```

```{r}
set.seed(99)
EV_data$nZEV <- as.numeric(as.character(EV_data$nZEV))

zip <- unique(EV_data$zip)
zip100 <- sample(zip,100)

EV_data_100 = EV_data[EV_data$zip %in% zip100, ]
EV_data_100$nZEV <- as.numeric(as.character(EV_data_100$nZEV))




p <- ggplot(data = EV_data_100, aes(x = yr, y = nZEV, group = zip)) + 
  geom_point() + 
  geom_line() + 
  ggtitle("100 Randomly Selected ZipCodes") +
  xlab("Year") + 
  ylab("Number of Zero Emission Vehicles") + 
  
  scale_y_continuous(breaks = seq(0, 5000, by = 1200) 
)
p
```

```{r}
par(mfrow = c(1,3))
#Histograms of RoA, ZEVs, Population
hist(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate, main = 'Rate of Asthma', xlab = 'Age Adjusted Rate of Asthma')
#hist(log_AgeAdj_RoA_ED_Visit_Rate, main = 'Log of Rate of Asthma', xlab = 'Age Adjusted Rate of Asthma')
hist(EV_data$nZEV, main ='Zero Emission Vehicles', xlab = '# of Zero Emission Vehicles')
hist(EV_data$pop, main ='Population', xlab = 'Population Count')
```

```{r}
#Histograms of Poverty rate, Median Income, Mean Income
par(mfrow = c(1,3))

hist(EV_data$percPoverty, main = 'Poverty Rate', xlab = 'Percent of Poverty')
hist(EV_data$HHincomeMedian, main ='Median Income', xlab = 'Annual Income')
hist(EV_data$HHincomeMean, main ='Mean Income', xlab = 'Annual Income')
```

```{r}
par(mfrow = c(1,2))
#Histograms of HS Education, BA Education
hist(EV_data$EDUCpercHSplus, main = 'HS Education', xlab = '% of 25+ w/ High School Diploma')
hist(EV_data$EDUCpercBAplus, main ='BA Education', xlab = "% of 25+ w/ Bachelor's Degree")
```


```{r}
#EV spaghetti plot
EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate <- as.numeric(as.character(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate))
library(scales)
zip = unique(EV_data$zip)
set.seed(100)
zip100 = sample(zip, 100)
EV_data_100 = EV_data[EV_data$zip %in% zip100,  ]
library(ggplot2)
EV_data_100 <- within(EV_data_100, {
  yr <- factor(yr)
  zip <- factor(zip)
  ED <- Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate
})

p <- ggplot(data = EV_data_100, aes(x = yr, y = ED ,group = zip, color = ED)) +
geom_point(size = 1.5) + 
  geom_line() + 
  scale_color_gradientn(
    colors = c("black", "darkred", "red"),
    values = rescale(c(0, 500, 5000))) +
  theme_classic() +
  ggtitle("100 Randomly Selected ZipCodes") +
  xlab("Year") + 
  ylab("Age Adjusted Rate of Asthma ED Visits") + 
  
 scale_y_continuous(breaks = seq(0, 5000, by = 1200)) +
theme_minimal()
p
```
```{r}
#nZEV spaghetti plot
EV_data$nZEV <- as.numeric(as.character(EV_data$nZEV))
EV_data_100$nZEV <- as.numeric(as.character(EV_data_100$nZEV))
zip <- unique(EV_data$zip)
set.seed(99)
zip100 <- sample(zip,100)
EV_data_100 = EV_data[EV_data$zip %in% zip100, ]

library(scales)
p <- ggplot(data = EV_data_100, aes(x = yr, y = nZEV, group = zip, color = nZEV)) + 
  geom_point(size = 1.5) + 
  geom_line() +
   scale_color_gradientn(
    colors = c("black", "darkred", "red"),
    values = rescale(c(0, 500, 5000))) +
  theme_classic() +

  ggtitle("100 Randomly Selected ZipCodes") +
  xlab("Year") + 
  ylab("Number of Zero Emission Vehicles") + 
  scale_y_continuous(breaks = seq(0, 5000, by = 1200))
theme_minimal()
p
```

```{r}

paste("Number of ZipCo:",length(unique(EV_data$zip)))

paste("Mean of population:", mean(EV_data$pop))
paste("Max of population:", max(EV_data$pop))
paste("Min of population",min(EV_data$pop))

paste("Mean of mean",mean(EV_data$EDUCpercHSplus))
sd(EV_data$EDUCpercHSplus)

mean(EV_data$EDUCpercBAplus)
sd(EV_data$EDUCpercBAplus)

median(EV_data$HHincomeMedian)
sd(EV_data$HHincomeMedian)

mean(EV_data$percPoverty)
sd(EV_data$percPoverty)

```
```{r}
EV_data |> filter(yr == 2013) |> tbl_summary(include = c(pop,HHincomeMedian,percPoverty,EDUCpercHSplus,EDUCpercBAplus),
                       statistic = list(all_continuous() ~ "{mean} ({sd})"))
```

```{r}
EV_data |> filter(yr %in% c(2013,2018,2022)) |> 
        mutate(yr = as.factor(yr)) |>
        tbl_summary(include = c(pop,HHincomeMedian,percPoverty,EDUCpercHSplus,EDUCpercBAplus),
                       statistic = list(all_continuous() ~ "{mean} ({sd})"),
                    by = yr )
```
