---
title: "Regression"
author: "Justin Coles,Jessy Garcia, Joseph Salamante"
date: "2025-06-30"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```



```{r}
library(ggplot2)
library(dplyr) 
getwd()
EV_data <- read.csv("./Data/data_ZEV_asthmaED_2013_2022.csv")
# Income vs. Log Asthma Rate Plot
# For 2013
EV_data$nZEV1000pop <- EV_data$nZEV/EV_data$pop *1000
EV_data$log_AgeAdj_RoA_ED_Visit_Rate <- log(EV_data$Age_Adjusted_Rate_of_Asthma_ED_Visit_Rate)
EV_data_2013 <- EV_data %>% filter( yr == 2013)
EV_data_2022 <- EV_data %>% filter( yr == 2022)
```

```{r}

ggplot(EV_data_2013, aes(x = HHincomeMedian, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  labs(
    title = "2013: Median Income vs Log Asthma ED Visit Rate",
    x = "Median Household Income ($)",
    y = "Log Asthma ED Visit Rate"
  )
```

```{r}

# For 2022
ggplot(EV_data_2022, aes(x = HHincomeMedian, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE, color = "darkgreen") +
  labs(
    title = "2022: Median Income vs Log Asthma ED Visit Rate",
    x = "Median Household Income ($)",
    y = "Log Asthma ED Visit Rate"
  )

```

```{r}

lm(EV_data_2013$log_AgeAdj_RoA_ED_Visit_Rate ~ EV_data_2013$percPoverty   , data = EV_data)
lm(EV_data_2022$log_AgeAdj_RoA_ED_Visit_Rate ~ EV_data_2022$percPoverty, data = EV_data)

#Poverty Percentage vs Log Asthma Rate
# 2013
ggplot(EV_data_2013, aes(x = percPoverty, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "red") +
  labs(
    title = "2013: Poverty % vs Log Asthma ED Visit Rate",
    x = "% Below Poverty Line",
    y = "Log Asthma ED Visit Rate"
  )

# 2022
ggplot(EV_data_2022, aes(x = percPoverty, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "purple") +
  labs(
    title = "2022: Poverty % vs Log Asthma ED Visit Rate",
    x = "% Below Poverty Line",
    y = "Log Asthma ED Visit Rate"
  )


```

```{r}
 
EV_data_2013 <- EV_data %>%
  filter( yr == 2013)
lm(EV_data_2013$log_AgeAdj_RoA_ED_Visit_Rate ~ EV_data_2013$EDUCpercBAplus   , data = EV_data)
EV_data_2022 <- EV_data %>%
  filter( yr == 2022)
lm(EV_data_2022$log_AgeAdj_RoA_ED_Visit_Rate ~ EV_data_2022$EDUCpercBAplus, data = EV_data)

#BA Education vs Log Asthma Rate 
# 2013
ggplot(EV_data_2013, aes(x = EDUCpercBAplus, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "orange") +
  labs(
    title = "2013: % with BA+ vs Log Asthma ED Visit Rate",
    x = "% with Bachelor's or Higher",
    y = "Log Asthma ED Visit Rate"
  )

# 2022
ggplot(EV_data_2022, aes(x = EDUCpercBAplus, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "darkorange") +
  labs(
    title = "2022: % with BA+ vs Log Asthma ED Visit Rate",
    x = "% with Bachelor's or Higher",
    y = "Log Asthma ED Visit Rate"
  )

```

```{r}
EV_data_2013 <- EV_data %>%
  filter( yr == 2013)
lm(EV_data_2013$log_AgeAdj_RoA_ED_Visit_Rate ~ EV_data_2013$nZEV1000pop   , data = EV_data)
EV_data_2022 <- EV_data %>%
  filter( yr == 2022)
lm(EV_data_2022$log_AgeAdj_RoA_ED_Visit_Rate ~ EV_data_2022$nZEV1000pop , data = EV_data)

# ZEVs per 1,000 vs Log Asthma
# 2013
ggplot(EV_data_2013, aes(x = nZEV1000pop, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "steelblue") +
  labs(
    title = "2013: ZEVs per 1,000 People vs Log Asthma Rate",
    x = "ZEVs per 1,000 People",
    y = "Log Asthma ED Visit Rate"
  )

# 2022
ggplot(EV_data_2022, aes(x = nZEV1000pop, y = log_AgeAdj_RoA_ED_Visit_Rate)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "forestgreen") +
  labs(
    title = "2022: ZEVs per 1,000 People vs Log Asthma Rate",
    x = "ZEVs per 1,000 People",
    y = "Log Asthma ED Visit Rate"
  )


```
```{r}
 pov <-lm(log_AgeAdj_RoA_ED_Visit_Rate ~ I(nZEV1000pop/10) + percPoverty, data= EV_data_2022)

 HH <- lm(log_AgeAdj_RoA_ED_Visit_Rate ~I(nZEV1000pop/10) + HHincomeMedian, data= EV_data_2022)

 EDUC <- lm(log_AgeAdj_RoA_ED_Visit_Rate ~ I(nZEV1000pop/10) +EDUCpercBAplus, data= EV_data_2022)
 
 summary(pov)
  summary(HH)
   summary(EDUC)


```
```{r}
exp(-5.608e-02)
exp(-0.0349378)

1-0.9454635
1-0.9656655

0.0545365 *100
0.0343345 *100
```


```{r}
#Mutli Linear Regression Model 2022

multi_model_2022_poverty <- lm(log_AgeAdj_RoA_ED_Visit_Rate ~ I(nZEV1000pop/10)   +  percPoverty, data= EV_data_2022)

summary(multi_model_2022_poverty)
```

```{r}
exp(-0.093791) 

(1- 0.910473) *100
```


```{r}
#Mutli Linear Regression Model 2022 No SES

multi_model_2022 <- lm(log_AgeAdj_RoA_ED_Visit_Rate ~ I(nZEV1000pop/10), data= EV_data_2022)

summary(multi_model_2022)
```

```{r}
exp(-0.128381)

(1 - 0.8795182) * 100
```


```{r}
# more data processing
EV_data$yrC <- EV_data$yr - 2013 # create a year variable centered at the first study year, 2013
EV_data$yrC2 <- EV_data$yrC^2 # squared centered year term to allow for nonlinear trends in time
EV_data$yrC3 <- EV_data$yrC^3 # cubic centered year term to allow for nonlinear trends in time (you might add this too!)

# code for random intercept longitudinal model (I'll draw this on the board for you)

# load nlme package to fit random effects (longitudinal) model
library(nlme)

# requires dataset to be non-missing in included variables
d_complete <- subset(EV_data,!is.na(nZEV1000pop) & !is.na(EDUCpercBAplus))

# fit model, with random intercept for zip
fit1 <- lme(log_AgeAdj_RoA_ED_Visit_Rate ~ nZEV1000pop + yrC + yrC2 + EDUCpercBAplus,
                            random=list(~1|zip),# random intercept at zip code level
                            data=d_complete,
                            method="REML")
summary(fit1)
intervals(fit1)

#class(d_complete$zip)
#factor(d_complete$zip)

# fit another model, with also a random slope on year
fit2 <- lme(log_AgeAdj_RoA_ED_Visit_Rate ~ nZEV1000pop + yrC + yrC2 + EDUCpercBAplus,
    #control=c(maxIter=5000),        
                            random=list(~yrC|zip),# random intercept at zip code level
                            data=d_complete,
                            method="REML")
summary(fit2)
intervals(fit2)

exp(0.002268)
(1.00227-1) * 100

```

